=== StefanSinapov/TelerikAcademy/11. Databases and SQL/14. XML Basics/0. Demos/library.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.nakov.com/schemas/library"
  targetNamespace="http://www.nakov.com/schemas/library">
  
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="book" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="author"/>
				<xs:element ref="isbn"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="title" type="xs:string"/>
	<xs:element name="author" type="xs:string"/>
	<xs:element name="isbn" type="xs:string"/>

</xs:schema>

=== StefanSinapov/TelerikAcademy/11. Databases and SQL/14. XML Basics/0. Demos/library-valid.xml
<?xml version="1.0"?>
<library xmlns="http://www.nakov.com/schemas/library"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.nakov.com/schemas/library file://./library.xsd"
  name=".NET Developer's Library">
	<book>
		<title>Professional C# 4.0 and .NET 4</title>
		<author>Christian Nagel</author>
		<isbn>978-0-470-50225-9</isbn>
	</book>
	<book>
		<title>Silverlight in Action</title>
		<author>Pete Brown</author>
		<isbn>978-1-935182-37-5</isbn>
	</book>
</library>
